/**
 * A self-contained HTML snapshot of copilot answers (from an L2 scripted run or an L3 live run),
 * for reading without deploying anything. Pure: every value is escaped; no script runs.
 */

export interface SnapshotEntry {
  id: string;
  title: string;
  question: string;
  status: string;
  answer: string | null;
  limitations: { code: string; description: string }[];
  toolCalls: { id: string; tool: string; input: unknown; isError: boolean; value: unknown; cited: boolean }[];
}

export interface SnapshotInput {
  level: "L2" | "L3";
  model: string;
  generatedAt: string;
  dataset: { asOf: string; repository: string; tag: string; commit: string; seed: number } | null;
  entries: SnapshotEntry[];
}

export function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
}

const STYLE = `
:root{--bg:#f7f7f5;--panel:#fff;--text:#1d1d1b;--muted:#61615c;--line:#e2e1dc;--accent:#2f6b4f;--warn:#8a5a00;--error:#a33a2c;--code:#f1f0ec}
@media (prefers-color-scheme:dark){:root{--bg:#161715;--panel:#1f201e;--text:#ecebe6;--muted:#a4a39c;--line:#34352f;--accent:#6fb08e;--warn:#e0b45a;--error:#f08a7a;--code:#272824}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:880px;margin:0 auto;padding:24px 16px 64px}h1{font-size:1.5rem;margin:0 0 6px}
.muted{color:var(--muted);font-size:.88rem}article{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0}
h2{font-size:1.05rem;margin:0 0 4px}.q{font-style:italic;margin:4px 0 10px}.a{font-size:1.02rem;white-space:pre-wrap}
.status{font-weight:600;font-size:.85rem}.answered{color:var(--accent)}.insufficient_data,.out_of_scope{color:var(--warn)}.incomplete,.format_error{color:var(--error)}
h3{font-size:.8rem;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:14px 0 4px}ul{margin:0;padding-left:20px}
details{border-top:1px solid var(--line);padding:5px 0}summary{cursor:pointer;font-size:.9rem;overflow-wrap:anywhere}
pre{background:var(--code);border-radius:8px;padding:10px;overflow-x:auto;font-size:.78rem;max-height:380px}nav a{color:var(--accent)}
`;

function entryHtml(entry: SnapshotEntry): string {
  const limitations = entry.limitations.length
    ? `<h3>Limitations</h3><ul>${entry.limitations.map((item) => `<li>${escapeHtml(item.description)}</li>`).join("")}</ul>`
    : "";
  const calls = entry.toolCalls.length
    ? `<h3>Sources and tool calls</h3>${entry.toolCalls
        .map(
          (call) =>
            `<details><summary>[${escapeHtml(call.id)}] ${escapeHtml(call.tool)} ${escapeHtml(JSON.stringify(call.input))}${call.isError ? " (error)" : ""}${call.cited ? "" : " (not cited)"}</summary><pre>${escapeHtml(JSON.stringify(call.value, null, 2))}</pre></details>`,
        )
        .join("")}`
    : "";
  return `<article id="${escapeHtml(entry.id)}"><h2>${escapeHtml(entry.id)} · ${escapeHtml(entry.title)}</h2>
<p class="q">${escapeHtml(entry.question)}</p>
<p class="status ${escapeHtml(entry.status)}">${escapeHtml(entry.status.replace("_", " "))}</p>
${entry.answer === null ? "" : `<p class="a">${escapeHtml(entry.answer)}</p>`}
${limitations}${calls}</article>`;
}

export function renderSnapshot(input: SnapshotInput): string {
  const how =
    input.level === "L2"
      ? "Answers come from a scripted model (evaluation level L2): it replays a fixed tool plan and a fixed answer written with placeholders, so every figure below was filled in from the real tool results. It shows the tools, validation and rendering, not a live model's choices."
      : `Answers come from the live model ${escapeHtml(input.model)} (evaluation level L3).`;
  const dataset = input.dataset
    ? `Data as of ${escapeHtml(input.dataset.asOf)}, generated by Project 1 ${escapeHtml(input.dataset.tag)} (commit ${escapeHtml(input.dataset.commit.slice(0, 12))}, seed ${input.dataset.seed}).`
    : "";
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Biomix Sales Copilot snapshot</title><style>${STYLE}</style></head>
<body><main>
<h1>Biomix Sales Copilot: answer snapshot</h1>
<p class="muted">A sales investigation copilot that answers questions about invoiced sales and scheduled collections by calling a fixed set of read-only tools, and cites the tool results behind every figure. All data is synthetic and fictional; scheduled installments are contractual amounts, not payments.</p>
<p class="muted">${how} ${dataset} Generated ${escapeHtml(input.generatedAt)}.</p>
<nav class="muted">${input.entries.map((entry) => `<a href="#${escapeHtml(entry.id)}">${escapeHtml(entry.id)}</a>`).join(" · ")}</nav>
${input.entries.map(entryHtml).join("\n")}
</main></body></html>
`;
}
